<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <script>
        // promise.resolve()와 promise.reject()는 자동으로(즉시) 성공하거나 실패하는 프로미스를 생성한다.

        // Promise.resolve()
        Promise.resolve('success').then(function(value){
            console.log('success');
            // success
        }, function(value){
            console.log('fail');
        });

        // 첫 번째 예제에서 볼 수 있듯이 .then() 절에서 생성된 프로미스에서 두 개의 인수가 있다.
        // 하나는 프로미스가 성공할 때 호출되는 함수이고, 다른 하나는 프로미스가 실패할 때 호출되는 함수이다.
        // Promise.resolve()는 즉시 프로미스를 성공 처리하므로 첫 번째 함수가 호출된다.


        // Promise.reject()
        Promise.reject(new Error('fail')).then(function(){
            // not called
        }, function(error){
        console.log(error);
            // Error : fail
        });

        // 두 번째 예제에서는 Promise.reject()를 사용하여 프로미스를 즉시 실패처리하므로 .then() 절의 두 번째 인수가 호출된다.

        
    </script>
</body>
</html>